services:
  wordpress1:
    image: wordpress
    restart: on-failure
    container_name: wordpress1
    environment:
      WORDPRESS_DB_HOST: 10.0.133.166
      WORDPRESS_DB_USER: hodhod
      WORDPRESS_DB_PASSWORD: hodhod0114496
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8080:80"
    volumes:
      - /var/www/html/wp-content/:/var/www/html/wp-content/

  wordpress2:
    image: wordpress
    restart: on-failure
    container_name: wordpress2
    environment:
      WORDPRESS_DB_HOST: 10.0.133.166
      WORDPRESS_DB_USER: hodhod
      WORDPRESS_DB_PASSWORD: hodhod0114496
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8081:80"
    volumes:
      - /var/www/html/wp-content/:/var/www/html/wp-content/

    depends_on:
      wordpress1:
        condition: service_started

  nginx:
    build:
      context: .
    ports:
      - 80:80
    restart: on-failure
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
